<?php

namespace AppBundle\Repository;

use Symfony\Component\HttpFoundation\ParameterBag;

/**
 * ChamadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChamadoRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param ParameterBag $data
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function search(ParameterBag $data)
    {
        $qb = $this->createQueryBuilder('c');
        
        if ($data->get('email')) {
            $qb->join('c.cliente', 'cl');
            $qb->where('cl.email = :email');
            $qb->setParameter('email', $data->get('email'));
        }
        
        if ($data->get('pedidoId')) {
            $qb->join('c.pedido', 'p');
            $qb->where('p.id = :pedidoId');
            $qb->setParameter('pedidoId', $data->get('pedidoId'));
        }
        
        return $qb;
    }
}
